#pragma once

#include "Coordinate.h"

namespace Algorithm {
  /**
   * Utility class to perform transformations on 3D points. Generated by Chat GPT.
   */
  class Matrix3D {
    public:
      CoordinateType matrix[4][4];

      Matrix3D();
      static Matrix3D identity();
      static Matrix3D translation(CoordinateType tx, CoordinateType ty, CoordinateType tz);
      static Matrix3D rotation(CoordinateType ax, CoordinateType ay, CoordinateType az);
      static Matrix3D rotationX(CoordinateType angle);
      static Matrix3D rotationY(CoordinateType angle);
      static Matrix3D rotationZ(CoordinateType angle);
      static Matrix3D scale(CoordinateType sx, CoordinateType sy, CoordinateType sz);

      Matrix3D operator*(const Matrix3D& other) const;
      void multiplyVec(const CoordinateType vec[4], CoordinateType result[4]) const;
  };
}